# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b443a667bf1dbfe1d8d41cb9ef93e3d92817d766108f490787009537d6e86aca294c8c4032738afc6e5a6b6a99c9d8ec823ec25232a5221d8d761efdc9ab0bc8
  twilio_number: "+7247130552"
  twilio_sid: ACd2d5d20649d8867fb49053530c6160f9
  twilio_auth_token: d3101c05c0501320f356795ad4a92e14
  twilio_test_sid: AC2be7d01f58234a83744342bcf1f2cfbd
  twilio_test_auth_token: 55be618aad2ee6e4700f1dacc51dd9ac

test:
  secret_key_base: 30429c826d9d386f8bb0a458c6baf31e825564437be4506a3e37627ca22ce3b5d3a6df6942a4899214bd7fe628dbe6e72ad4e28231f9ed3efb86da1be2e8f934

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= SETTINGS[:secret_key_base] %>
